-- MySQL Script generated by MySQL Workbench
-- Sun Mar 14 21:27:49 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema twitter
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `twitter` DEFAULT CHARACTER SET utf8 ;
USE `twitter` ;

-- -----------------------------------------------------
-- Table `twitter`.`usuário`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `twitter`.`usuário` (
  `idTwitter` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  `nick` VARCHAR(45) NULL,
  PRIMARY KEY (`idTwitter`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `twitter`.`tweet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `twitter`.`tweet` (
  `idLink` VARCHAR(45) NOT NULL,
  `texto` VARCHAR(45) NULL,
  `data` DATETIME NULL,
  `usuário_idTwitter` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idLink`, `usuário_idTwitter`),
  INDEX `fk_tweet_usuário1_idx` (`usuário_idTwitter` ASC) VISIBLE,
  CONSTRAINT `fk_tweet_usuário1`
    FOREIGN KEY (`usuário_idTwitter`)
    REFERENCES `twitter`.`usuário` (`idTwitter`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `twitter`.`retweets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `twitter`.`retweets` (
  `usuário_idTwitter` VARCHAR(45) NOT NULL,
  `tweet_idLink` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`usuário_idTwitter`, `tweet_idLink`),
  INDEX `fk_usuário_has_tweet_tweet1_idx` (`tweet_idLink` ASC) VISIBLE,
  INDEX `fk_usuário_has_tweet_usuário1_idx` (`usuário_idTwitter` ASC) VISIBLE,
  CONSTRAINT `fk_usuário_has_tweet_usuário1`
    FOREIGN KEY (`usuário_idTwitter`)
    REFERENCES `twitter`.`usuário` (`idTwitter`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuário_has_tweet_tweet1`
    FOREIGN KEY (`tweet_idLink`)
    REFERENCES `twitter`.`tweet` (`idLink`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `twitter`.`curtidas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `twitter`.`curtidas` (
  `usuário_idTwitter` VARCHAR(45) NOT NULL,
  `tweet_idLink` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`usuário_idTwitter`, `tweet_idLink`),
  INDEX `fk_usuário_has_tweet1_tweet1_idx` (`tweet_idLink` ASC) VISIBLE,
  INDEX `fk_usuário_has_tweet1_usuário1_idx` (`usuário_idTwitter` ASC) VISIBLE,
  CONSTRAINT `fk_usuário_has_tweet1_usuário1`
    FOREIGN KEY (`usuário_idTwitter`)
    REFERENCES `twitter`.`usuário` (`idTwitter`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuário_has_tweet1_tweet1`
    FOREIGN KEY (`tweet_idLink`)
    REFERENCES `twitter`.`tweet` (`idLink`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
